project:
  type: website

website:
  title: "Achilleas Kouventaras"
  navbar:
    title: "Achilleas Kouventaras"
    right:
      - icon: github
        href: https://github.com/achilleaskouventaras
      - icon: linkedin
        href: https://www.linkedin.com/in/achilleas-kouventaras/
format:
  html:
    theme: cosmos
    css: styles.css
    backgroundcolor: "#faf9f6"
    
editor: visual

