project:
  type: website

website:
  title: "portfolio"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/achilleaskouventaras
      - icon: linkedin
        href: https://www.linkedin.com/in/achilleas-kouventaras/
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

