project:
  type: website

website:
  title: "Achilleas Kouventaras"
  navbar:
    left:
    - text: Home
      href: index.qmd
    - text: Projects
      href: projects.qmd
    right:
      - about.qmd
      - icon: github
        href: https://github.com/achilleaskouventaras
      - icon: linkedin
        href: https://www.linkedin.com/in/achilleas-kouventaras/
format:
  html:
    theme: cosmos
    css: styles.css

editor: visual

